### ISSUE TITLE
SP2: GPS sensor configuration in user space.

### ISSUE THREAD

**Issue by prvbharadwaj1731** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#7]
DoD

- Successfully connect to GPS sensor over UART on the Beaglebone Black.  --> COMPLETED
- Writing GPS co-ordinates received from sensor to a file or printing the co-ordinates. --> COMPLETED

**Comment by Ganeshkm10** [comment]
Update:  Initially wanted to keep the GPS library and GPS user space code separate. Hence Two issues were created. [ [Userspace](https://github.com/cu-ecen-aeld/final-project-TejaswiniLakshminarayan/issues/7) and [GPS Library](https://github.com/cu-ecen-aeld/final-project-TejaswiniLakshminarayan/issues/9). However, these two were merged and implemented as part of this sprint.

Testing: Tested on Debian distribution on Beaglebone, However because of the UART patch problem for the buildroot image, Still have to test on our image. 

Refer Commit ID [here](https://github.com/cu-ecen-aeld/final-project-Ganeshkm10/commit/fb9edc739fff6659e3ba257feb46068f8648e579)

![image](https://user-images.githubusercontent.com/32218214/202964097-3ff91b89-0c7e-43c9-bfe5-dda650f36ab9.png)
