### ISSUE TITLE
SP2: GPS library integration

### ISSUE THREAD

**Issue by prvbharadwaj1731** [cu-ecen-aeld/final-project-TejaswiniLakshminarayan#9]
DoD:

- Succesful integration of library chosen from previous analysis [Refer here](https://github.com/cu-ecen-aeld/final-project-TejaswiniLakshminarayan/issues/8)   -->  COMPLETED
- Testing it on the Beaglebone with the GPS sensor.   - -> VERIFIED

**Comment by Ganeshkm10** [comment]
Installed gpsd on beaglebone and UART 4 was enabled and connected with GPS sensor.
If we have to design custom uart. Using this deamon would be difficult to integrate. 

![image](https://user-images.githubusercontent.com/32218214/202887316-b3574ec7-bec7-46f3-97d8-bd78d8e973bd.png)

**Comment by Ganeshkm10** [comment]
Update: GPS library is integrated and can be found in this [commit id](https://github.com/cu-ecen-aeld/final-project-Ganeshkm10/commit/fb9edc739fff6659e3ba257feb46068f8648e579)

**Comment by Ganeshkm10** [comment]
Started with the plan to have a static library for the GPS But while implementing both the library code and the user space code were merged. 

Testing: Tested with Debian distribution. Since UART is still not enabled on the buildroot image. could not test that on our image. However, it is running without any errors. 

Commit id: [Refer Here](https://github.com/cu-ecen-aeld/final-project-Ganeshkm10/commit/fb9edc739fff6659e3ba257feb46068f8648e579)

![image](https://user-images.githubusercontent.com/32218214/202963149-7e885836-c121-4f4e-8dca-49f4ad3cfc72.png)
